<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getAllSorted(){
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->addOrderBy('b.created', 'DESC'); 
            
//        return $qb->getQuery()->getResult(); //when using pagination, you don't want the result, you want the query
        
        return $qb->getQuery();
    }
    
}
