<?php

namespace AppBundle\Entity\Repository;
use Doctrine\Common\Collections\Criteria;
/**
 * ComplaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintRepository extends \Doctrine\ORM\EntityRepository
{
    //override default findall and sort by timestamp:
    public function findAll()
    {
        return $this->findBy(array(), array('timestamp' => 'DESC'));
    }
    
    public function getAll(){
        $qb = $this->createQueryBuilder('c')->select('c');
//        $qb->getQuery()->getResult();
//        $ar = array();
//        foreach($qb->getTimestamp() as $result){
//            
//        }
        return $qb->getQuery()->getResult();
    }
    
    public function getUnresolvedComps($user = null){
        if($user == null){
            $qb = $this->createQueryBuilder('c')->select('c');
            $qb->where('c.is_resolved = false');
            return $qb->getQuery()->getResult();
        }else{
            $complaints = $user->getComplaints();
            $newerCriteria = Criteria::create()
                            ->where(Criteria::expr()->gt("is_resolved", false));
        
            return $complaints->matching($newerCriteria);
        }
        
    }
    
    public function getResolvedComps($user = null){
        if($user == null){
            $qb = $this->createQueryBuilder('c')->select('c');
            $qb->where('c.is_resolved = true');
            return $qb->getQuery()->getResult();
        }else{
            $complaints = $user->getComplaints();
            $newerCriteria = Criteria::create()
                            ->where(Criteria::expr()->gt("is_resolved", true));
        
            return $complaints->matching($newerCriteria);
        }
    }
}
