<?php

namespace AppBundle\Entity\Repository;

/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLast(){
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->orderBy('c.id', 'DESC')
                ->setMaxResults(1);
        
        return $qb->getQuery()->getSingleResult();
        
    }
}
