<?php

namespace AppBundle\Entity\Repository;

/**
 * MinutesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinutesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIdOfLast() {
        $query = $this->createQueryBuilder('m')
                ->select('m.id')
                ->orderBy('m.created', 'DESC')
                ->setMaxResults(1);
        
        $result = $query->getQuery()->getOneOrNullResult();
        
        return null == $result ? null : $result['id'];
    }
           
    public function getSortedMinutes(){
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                   ->addOrderBy('m.created', 'DESC');
        
        return $qb->getQuery()
                  ->getResult();
    }
    
}
