<?php

namespace AppBundle\Entity\Repository;

/**
 * PermitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getResolvedPermits(){
        $qb = $this->createQueryBuilder('p')
                   ->select('p')
                   ->where('p.is_approved is not null')
                   ->orWhere('p.is_denied is not null');
        
        return $qb->getQuery()
                  ->getResult();
    }
    
    public function getUnresolvedPermits(){
        $qb = $this->createQueryBuilder('p')
                   ->select('p')
                   ->where('p.is_approved is null')
                   ->andWhere('p.is_denied is null');
        
        return $qb->getQuery()
                  ->getResult();
    }
    
    public function getApprovedPermits(){
        $qb = $this->createQueryBuilder('p')
                   ->select('p')
                   ->where('p.is_approved = 1');
        
        return $qb->getQuery()
                  ->getResult();
    }
    
    public function getDeniedPermits(){
        $qb = $this->createQueryBuilder('p')
                   ->select('p')
                   ->where('p.is_denied = 1');
        
        return $qb->getQuery()
                  ->getResult();
    }
}
