<?php

namespace AppBundle\Entity\Repository;

/**
 * ProgressNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressNoteRepository extends \Doctrine\ORM\EntityRepository
{

}
