<?php

namespace AppBundle\Entity\Repository;

/**
 * SchoolDistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolDistrictRepository extends \Doctrine\ORM\EntityRepository
{
}
