<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionsRepository extends EntityRepository
{
    //override the default findAll method and add sort:
    public function findAll()
    {
        return $this->findBy(array(), array('created_at' => 'DESC'));
    }
    
    public function getAccountTransactions($account, $days = null){
        //$days is optional.  Set $days to limit the results to the # of days you want to go back
        $transactions = $this->createQueryBuilder('t')
             ->add('select', 't')
             ->add('from', 'AppBundle:Transactions t')
             ->innerJoin('AppBundle:Account', 'a')
             ->where('t.account = :account')
             ->setParameter('account', $account);
               if(isset($days)){
                    $transactions
                            ->andWhere('t.created_at >= :interval')
                            ->setParameter('interval', new \DateTime("-$days days"));
                }
        $transactions
            ->orderBy('t.created_at', 'DESC');
             
             return $transactions->getQuery()->getResult();
              
    }
}
